name: generate metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TROPHY_TOKEN }}
          user: Wahid1178
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
